---
- name: installing packages
  hosts: web_nodes
  become: yes
  tasks:
    - name: installing httpd server
      yum:
        name: httpd
        state: latest

    - name: Enable the servie to boot up
      service:
         name: httpd
         state: started
    
    - name: Restart apache service
      service:
         name: httpd
         state: restarted 
