## playbook to manage users using ansible
---
- name: Managing users account on remote servers
  hosts: web_nodes
  become: yes
  become_user: root
  tasks:
    - name: To remove user account (Naman) on target server 
      user:
        name: naman
        state: absent
        remove: yes

- name: Creating a user account (name provided during execution) to target nodes
  hosts: ansible_target
  become: yes
  become_user: root
  tasks:
    - name: Add {{ sudo_user }}
      user:
        name: "{{sudo_user}}"
        groups: wheel
        append: yes
        state: present
        password: $2a$04$rCwH4pT9u/uqmnI9sJ8UnOeicIscQxGA/sdmcgz7N/KBdkzl.jlr.
        createhome: yes
    - name: Make sudo without password for {{ sudo_user }} user
      copy:
        dest: /etc/sudoers.d/80-ansible-sudo-user
        content: "{{ sudo_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: 0440






